const zeniusAudioEnum = {
    tu_esi_sudas: "tu esi sudas",
    as_kasiaka_rukau: "as kasiaka rukau",
    as_tave_sveikinu: "as tave sveikinu",
    atsiradau: "atsiradau",
    auksinis_pydaras: "auksinis pydaras",
    balas_desimt: "balas desimt",
    drakula: "drakula",
    how_du_du: "how du du",
    kebabas: "kebabas",
    labai_malonu: "labai man malonu",
    manaroska: "manaroska",
    medis: "medis",
    myliu_tave: "myliu tave",
    obuoly: "obuoly",
    plikai_sneka: "plikai sneka",
    pydariau: "pydariau",
    sikni: "sikni",
    suesiu_tave: "suesiu tave",
    tau_i_strele: "pasaudysiu tau i strele",
    tava_pimpala: "tavo pimpala",
    tu_kaip_kriaukle: "tu kaip kriaukle",
    viena_pratyba: "viena pratyba",
    zombis: "zombis",
    hau_hau: "hau hau",
    gandashoks: "gandashoks",
    toki_ziauru: "toki ziauru",
    geda: "geda",
    masinas_nebereikia: "masinos nebereikia",
    nuo_sirdies: "nuo sirdies",
    pavalgai_atsisedes: "pavalgai atsisedes",
    savarma: "savarma",
    smegenys_is_proto_iseja: "smegenys is proto iseja",
    sunkoka_atsakyti: "sunkoka atsakyti",
    svarstukai: "svarstukai",
    tu_dabar_esi_berniukas: "tu dabar esi berniukas",
    ameno: "ameno",
    atrobuojanti: "atrobuojanti",
    auch_auch: "auch auch",
    bomzas: "bomzas",
    burna_pradziutu: "burna pradziutu",
    dziungle_is_afrikos: "dziungle is afrikos",
    is_kur_atsirado_dziungle: "is kur atsirado dziungle",
    ispaniskai: "ispaniskai",
    ka_cia_tai_reiskai: "ka cia tai reiskia",
    kodel_taip_zmones_sako: "kodel taip zmones sako",
    koks_linksmumas: "koks linksmumas",
    magyla: "magyla",
    mesa_suspaudzia: "mesa suspaudzia",
    nenormalus: "nenormalus",
    obuoli_suvalgai: "obuoli suvalgai",
    po_viena_troba: "po viena troba",
    puse_zmonus_puse_bezdzione: "puse zmogus puse bezdzione",
    simta_balu: "simta balu",
    su_liezuviu: "su liezuviu",
    sutraisysiu: "sutraiskysiu",
    traukinys_ramiai_stovi: "traukinys ramiai stovi",
    tu_pritriesi: "tu pritriesi",
    uch_uch: "uch uch",
    i_dont_understand_lithuanian: "i dont understand lithuanian"
}


module.exports = zeniusAudioEnum;