const zeniusAudioEnum = {
    tu_esi_sudas: "tu esi sudas",
    as_kasiaka_rukau: "as kasiaka rukau",
    as_tave_sveikinu: "as tave sveikinu",
    atsiradau: "atsiradau",
    auksinis_pydaras: "auksinis pydaras",
    balas_desimt: "balas desimt",
    drakula: "drakula",
    how_du_du: "how du du",
    kebabas: "kebabas",
    labai_malonu: "labai man malonu",
    manaroska: "manaroska",
    medis: "medis",
    myliu_tave: "myliu tave",
    obuoly: "obuoly",
    plikai_sneka: "plikai sneka",
    pydariau: "pydariau",
    sikni: "sikni",
    suesiu_tave: "suesiu tave",
    tau_i_strele: "pasaudysiu tau i strele",
    tava_pimpala: "tavo pimpala",
    tu_kaip_kriaukle: "tu kaip kriaukle",
    viena_pratyba: "viena pratyba",
    zombis: "zombis",
    hau_hau: "hau hau",
    gandashoks: "gandashoks",
    toki_ziauru: "toki ziauru",
    geda: "geda",
    masinas_nebereikia: "masinos nebereikia",
    nuo_sirdies: "nuo sirdies",
    pavalgai_atsisedes: "pavalgai atsisedes",
    savarma: "savarma",
    smegenys_is_proto_iseja: "smegenys is proto iseja",
    sunkoka_atsakyti: "sunkoka atsakyti",
    svarstukai: "svarstukai",
    tu_dabar_esi_berniukas: "tu dabar esi berniukas"
}


module.exports = zeniusAudioEnum;